declare module '*.svg'
declare module '*.png'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.bmp'
declare module '*.jpg'
declare module '*.png'
declare module '*.scss'
declare module '*.html'

declare module 'reactComp/*'
declare module 'appDir/*'
